# Vagrantfile

$install_script = <<-EOT
#!/bin/bash

yum install -y wget unzip acpid

# install the Consul binary
wget -nv https://releases.hashicorp.com/consul/1.8.5/consul_1.8.5_linux_amd64.zip -O consul.zip
unzip -o consul.zip
sudo chown root:root consul
sudo mv -fv consul /usr/sbin/
rm -fv consul.zip

# install the Nomad binary
wget -nv https://releases.hashicorp.com/nomad/0.12.7/nomad_0.12.7_linux_amd64.zip -O nomad.zip
unzip -o nomad.zip
sudo chown root:root nomad
sudo mv -fv nomad /usr/sbin/
rm -fv nomad.zip

# install Consul's service file
wget -nv https://raw.githubusercontent.com/shantanugadgil/hashistack/master/systemd/consul.service -O consul.service
sudo chown root:root consul.service
sudo mv -fv consul.service /etc/systemd/system/consul.service

# install Nomad's service file
wget -nv https://raw.githubusercontent.com/shantanugadgil/hashistack/master/systemd/nomad.service -O nomad.service
sudo chown root:root nomad.service
sudo mv -fv nomad.service /etc/systemd/system/nomad.service

sudo systemctl daemon-reload
EOT

Vagrant.configure("2") do |config|
  config.vm.box = "shantanug/centos-7-docker"
  config.vm.box_version = "0.0.1"
  config.vm.network "public_network", bridge: ["wlp5s0", "enp3s0"]
  config.vm.provision "shell", inline: $install_script

  1.upto(1) do |num|
    vmName = "srv#{num}"
    #vmIP = "192.68.50.1#{num}"
    config.vm.define vmName do |client|
      client.vm.hostname = vmName
    end
  end

  1.upto(1) do |num|
    vmName = "lb#{num}"
    #vmIP = "192.68.50.1#{num}"
    config.vm.define vmName do |client|
      client.vm.hostname = vmName
    end
  end

  1.upto(2) do |num|
    vmName = "client#{num}"
    #vmIP = "192.68.50.1#{num}"
    config.vm.define vmName do |client|
      client.vm.hostname = vmName
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
end
